addons:
  apt:
    packages:
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - cmake
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly