[package]
name = "vulkan-tutorial"
version = "0.1.0"
authors = ["André Twupack <atwupack@mailbox.org>"]

[dependencies]
clap = "2.30.0"
vulkano = "0.7.2"
vk-sys = "0.3.2"
glfw ={version = "0.21.0", features = ["vulkan"]}
vulkano-glfw = "0.3.0"